<a href="https://colab.research.google.com/github/Vanshu2374/data-science-45-days/blob/main/grass.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello

In [ ]:
# json
import pandas as pd
import numpy as np
url = "https://raw.githubusercontent.com/Vanshu2374/grass/main/file3%20json.json"
df = pd.read_json(url)
df.shape # rows -> 5 and cols -> 3
df["salary"] = [100,200,300,np.nan,500]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   name     5 non-null      object
 1   roll no  5 non-null      int64
 2   marks    5 non-null      int64
 3   salary   4 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 292.0+ bytes

In [ ]:
# head -> starting 5 rows
print(df.head())
# head -> 2 rows data
print(df.head(2))

# tail used for get last 5 rows data
df.tail(2)
# tail in negative
df.tail(-1)

       name  roll no  marks
0   dheeraj      123     10
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50
      name  roll no  marks
0  dheeraj      123     10
1    kunal     1234     20

       name  roll no  marks
1     kunal     1234     20
2  abhishek    12345     30
3   praveen    12356     40
4    anjali  1234567     50

In [ ]:
# rename
import pandas as pd
url = "https://raw.githubusercontent.com/Vanshu2374/grass/main/file3%20json.json"
df = pd.read_json(url)
df.rename(columns={"name":"student_name","marks":"salary"},inplace=True)
df

  student_name  roll no  salary
0      dheeraj      123      10
1        kunal     1234      20
2     abhishek    12345      30
3      praveen    12356      40
4       anjali  1234567      50

In [ ]:
import pandas as pd
url = "https://raw.githubusercontent.com/Vanshu2374/grass/main/file3%20json.json"
df = pd.read_json(url)
df.describe()

            roll no      marks
count  5.000000e+00   5.000000
mean   2.521250e+05  30.000000
std    5.492329e+05  15.811388
min    1.230000e+02  10.000000
25%    1.234000e+03  20.000000
50%    1.234500e+04  30.000000
75%    1.235600e+04  40.000000
max    1.234567e+06  50.000000

In [ ]:
import pandas as pd
data = {"Emp_id":[101,102,103,104,105,106],
        "Name":["amit","riya","raj","sara","john","neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]
        }
df = pd.DataFrame(data)
print(df)

   Emp_id  Name Department  Salary  Experience
0     101  amit         IT   50000           2
1     102  riya         HR   45000           3
2     103   raj    Finance   60000           5
3     104  sara         IT   55000           4
4     105  john      Sales   48000           1
5     106  neha         HR   52000           3

In [ ]:
import pandas as pd
data = {"Emp_id":[101,102,103,104,105,106],
        "Name":["amit","riya","raj","sara","john","neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]
        }
df = pd.DataFrame(data)

# head -> starting 5 rows
print(df.head())
# head -> 2 rows data
print(df.head(2))

# tail used for get last 5 rows data
df.tail(2)
# tail in negative
df.tail(-1)

   Emp_id  Name Department  Salary  Experience
0     101  amit         IT   50000           2
1     102  riya         HR   45000           3
2     103   raj    Finance   60000           5
3     104  sara         IT   55000           4
4     105  john      Sales   48000           1
   Emp_id  Name Department  Salary  Experience
0     101  amit         IT   50000           2
1     102  riya         HR   45000           3

   Emp_id  Name Department  Salary  Experience
1     102  riya         HR   45000           3
2     103   raj    Finance   60000           5
3     104  sara         IT   55000           4
4     105  john      Sales   48000           1
5     106  neha         HR   52000           3

In [ ]:
import pandas as pd
import numpy as np
data = {"Emp_id":[101,102,103,104,105,106],
        "Name":["amit","riya","raj","sara","john","neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]
        }
df = pd.DataFrame(data)
df.shape # rows -> 5 and cols -> 3
df["roll_no"] = [100,200,300,np.nan,500,600]
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Emp_id      6 non-null      int64
 1   Name        6 non-null      object
 2   Department  6 non-null      object
 3   Salary      6 non-null      int64
 4   Experience  6 non-null      int64
 5   roll_no     5 non-null      float64
dtypes: float64(1), int64(3), object(2)
memory usage: 420.0+ bytes

In [ ]:
import pandas as pd
data = {"Emp_id":[101,102,103,104,105,106],
        "Name":["amit","riya","raj","sara","john","neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]
        }
df = pd.DataFrame(data)
df.rename(columns={"Emp_id":"ID"},inplace=True)
df

    ID  Name Department  Salary  Experience
0  101  amit         IT   50000           2
1  102  riya         HR   45000           3
2  103   raj    Finance   60000           5
3  104  sara         IT   55000           4
4  105  john      Sales   48000           1
5  106  neha         HR   52000           3

In [ ]:
import pandas as pd
data = {"Emp_id":[101,102,103,104,105,106],
        "Name":["amit","riya","raj","sara","john","neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]
        }
df = pd.DataFrame(data)
df.describe()

           Emp_id        Salary  Experience
count    6.000000      6.000000    6.000000
mean   103.500000  51666.666667    3.000000
std      1.870829   5316.640543    1.414214
min    101.000000  45000.000000    1.000000
25%    102.250000  48500.000000    2.250000
50%    103.500000  51000.000000    3.000000
75%    104.750000  54250.000000    3.750000
max    106.000000  60000.000000    5.000000

In [ ]:
# operation on columns
import pandas as pd
url = "https://raw.githubusercontent.com/Vanshu2374/grass/main/file3%20json.json"
df = pd.read_json(url)
# get single column data
df["name"]
# add single column
df["salary"] = df["marks"] + 100
# add single column
df["salary"] = [100,200,300,400,500]
df

       name  roll no  marks  salary
0   dheeraj      123     10     100
1     kunal     1234     20     200
2  abhishek    12345     30     300
3   praveen    12356     40     400
4    anjali  1234567     50     500

In [ ]:
import pandas as pd
d = {
"name":["vishal","virat","vineet"], # 3 rows
"salary":[100,200,300] # 3 rows
}
df = pd.DataFrame(data=d)
# add column
df["marks"] = [10,20,30]
#df["marks"] = df["salary"] / 2
df["increment"] = df["salary"] + (df["salary"] / 10)
# column name change
df.rename(columns={"increment":"salary_increment"},inplace=True)
df

     name  salary  marks  salary_increment
0  vishal     100     10             110.0
1   virat     200     20             220.0
2  vineet     300     30             330.0

In [8]:
import pandas as pd
d = {
"name":["vishal","virat","vineet"], # 3 rows
"salary":[100,200,300] # 3 rows
}
df = pd.DataFrame(data=d)
# add columns
df["holidays"] = df["salary"] / 100
df["decrement"] = [10,20,30]
# delete column
df.drop(["salary","name"],axis=1,inplace=True)
df

   holidays  decrement
0       1.0         10
1       2.0         20
2       3.0         30

In [9]:
# operations on rows
import pandas as pd
d = {
"name":["vishal","virat","vineet"], # 3 rows
"salary":[100,200,300] # 3 rows
}
df = pd.DataFrame(data=d)
df

     name  salary
0  vishal     100
1   virat     200
2  vineet     300

In [21]:
print(df.loc[2,"name"])
print(df.iloc[2,0])

# get single row data
print(df.iloc[1])

# get single row using loc
print(df.loc[1])

# get multi rows using iloc
print(df.iloc[0:3])

# get multi rows using loc
print(df.loc[0:3])

# sub data get using iloc
df1 = df.iloc[0:2,[0]] # rows -> 0,1 and cols -> 0 | name
df1

# sub data get using loc
df2 = df.loc[0:2,"name"]
df2

vineet
vineet
name      virat
salary      200
Name: 1, dtype: object
name      virat
salary      200
Name: 1, dtype: object
     name  salary
0  vishal     100
1   virat     200
2  vineet     300
     name  salary
0  vishal     100
1   virat     200
2  vineet     300

0    vishal
1     virat
2    vineet
Name: name, dtype: object

In [33]:
import pandas as pd
data = {"Emp_id":[101,102,103,104,105,106],
        "Name":["amit","riya","raj","sara","john","neha"],
        "Department":["IT","HR","Finance","IT","Sales","HR"],
        "Salary":[50000,45000,60000,55000,48000,52000],
        "Experience":[2,3,5,4,1,3]
        }
df = pd.DataFrame(data)

# add column
df["experience"] = [10,20,30,40,50,60]
#df["salary"] = df["salary"] - 20000
#df["increment"] = df["salary"] + (df["salary"] / 10)
# column name change
df.rename(columns={"salary":"bonus"})

# get single row data
print(df.iloc[1])

# get single row using loc
print(df.loc[1])

# get multi rows using iloc
print(df.iloc[0:3])

# get multi rows using loc
print(df.loc[0:3])

# sub data get using iloc
df1 = df.iloc[0:2,[0]] # rows -> 0,1 and cols -> 0 | name
df1

Emp_id          102
Name           riya
Department       HR
Salary        45000
Experience        3
experience       20
Name: 1, dtype: object
Emp_id          102
Name           riya
Department       HR
Salary        45000
Experience        3
experience       20
Name: 1, dtype: object
   Emp_id  Name Department  Salary  Experience  experience
0     101  amit         IT   50000           2          10
1     102  riya         HR   45000           3          20
2     103   raj    Finance   60000           5          30
   Emp_id  Name Department  Salary  Experience  experience
0     101  amit         IT   50000           2          10
1     102  riya         HR   45000           3          20
2     103   raj    Finance   60000           5          30
3     104  sara         IT   55000           4          40

   Emp_id
0     101
1     102